# Generated by Django 4.2.8 on 2024-01-09 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_ban_right_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 12, 48, 37, 169224, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_last_ban',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 12, 48, 37, 169254, tzinfo=datetime.timezone.utc)),
        ),
    ]
