# Generated by Django 4.2.8 on 2024-01-10 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_is_ban_right_now_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 21, 44, 57, 382228, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_last_ban',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 21, 44, 57, 382263, tzinfo=datetime.timezone.utc)),
        ),
    ]
